name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_DEV }}
          username: ${{ secrets.SERVER_DEV_USERNAME }}
          password: ${{ secrets.SERVER_DEV_PASSWORD }}
          script: |
            ls
           # cd ${{ secrets.PROJECT_PATH_DEV }}
           # git reset --hard
           # git pull
           # npm i
           # npm run build
           # pm2 restart ecosystem.config.js
